version: '3.7'

services:
  nodejs:
      image: node-backend:v1
      build: ./backend
      restart: always
      command: npm run dev
      ports:
        - "5000:8080"
      env_file: 
        - ./backend/.env
     

  # angular:
  #   image: angular-frontend:v2
  #   build: ./frontend
  #   ports:
  #     - "4200:80"
  #   environment:
  #     - apiUrl=http://localhost:5000/api
  #     - storageUrl=http://localhost:5000/
  
  